config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'home#index'

  resources :frequency_analysis, only: :index do
    collection do
      post :compute
    end
  end

  resources :ceaser_cipher, only: :index do
    collection do
      post :compute
    end
  end

  resources :decrypt_ceaser, only: :index do
    collection do
      post :compute
    end
  end

  resources :vigenere_cipher, only: :index do
    collection do
      post :compute
    end
  end

  resources :rsa, only: :index do
    collection do
      post :compute
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/result.rb
class Result < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/ceaser_cipher_controller.rb
class CeaserCipherController < ApplicationController
  def index
    @shift = params[:shift]
    @show = params[:show]
  end

  def compute
    @cipher = CeaserCipherService.new(ceaser_params[:body],
                                      ceaser_params[:lang],
                                      ceaser_params[:shift]
                                     ).call
    Result.create(before: ceaser_params[:body], after: @cipher)

    redirect_to action: 'index',
                shift: ceaser_params[:shift],
                show: true
  end

  private

  def ceaser_params
    params.permit(:body, :lang, :shift)
  end
end

app/controllers/decrypt_ceaser_controller.rb
class DecryptCeaserController < ApplicationController
  def index
    @show = params[:show]
  end

  def compute
    @decrypted = DecryptCeaserService.new(ceaser_params[:body]).call
    Result.create(before: ceaser_params[:body], after: @decrypted)
    redirect_to action: 'index', show: true
  end

  private

  def ceaser_params
    params.permit(:body)
  end
end

app/controllers/frequency_analysis_controller.rb
class FrequencyAnalysisController < ApplicationController
  def index
    @frequency_analysis = params[:frequency_analysis]
  end

  def compute
    @frequency_analysis = FrequencyAnalysisService.new(body_param).call
    redirect_to action: 'index', frequency_analysis: @frequency_analysis
  end

  private

  def body_param
    frequency_param[:body]
  end

  def frequency_param
    params.permit(:body)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/rsa_controller.rb
class RsaController < ApplicationController
  def index
    @show = params[:show]
  end

  def compute
    @rsa_data = RsaCipherService.new(rsa_params[:body]).call
    Result.create(before: rsa_params[:body], after: @rsa_data)
    redirect_to action: 'index', show: true
  end

  private

  def rsa_params
    params.permit(:body)
  end
end

app/controllers/vigenere_cipher_controller.rb
class VigenereCipherController < ApplicationController
  def index
    @show = params[:show]
  end

  def compute
    @encrypted = VigenereCipherService.new(vigenere_params[:body],
                                           vigenere_params[:seq],
                                           vigenere_params[:lang]).call
    Result.create(before: vigenere_params[:body], after: @encrypted)
    redirect_to action: 'index', show: true
  end

  private

  def vigenere_params
    params.permit(:body, :seq, :lang)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ceaser_cipher_helper.rb
module CeaserCipherHelper
end

app/helpers/decrypt_ceasar_helper.rb
module DecryptCeasarHelper
end

app/helpers/frequency_analysis_helper.rb
module FrequencyAnalysisHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/rsa_helper.rb
module RsaHelper
end

app/helpers/vigenere_cipher_helper.rb
module VigenereCipherHelper
end

app/views/ceaser_cipher/index.html.erb
<p>
  <%= link_to 'Головна', root_path %>
</p>
<div class="text-center">
  <h1>Шифр зсуву для латинського та українсього алфавітів:</h1>

  <% if @show %>
    <p>Текст до шифрування: <br/> <%= Result.last.before %></p>
    <p>Зсув: <br/> <%= @shift %></p>
    <p>Результат шифрування: <br/> <%= Result.last.after %></p>
  <% end %>

  <%= form_tag(compute_ceaser_cipher_index_path, method: :post) do -%>
    <p class="text-bold mt">Введіть текст для шифрування</p>
    <div class="mt">
      Мова:
      <%= select_tag 'lang', options_for_select(["ua", "en"]), include_blank: false %>
    </div>
    <div class="mt">
      Зсув:
      <%= number_field_tag 'shift', include_blank: false %>
    </div>
    <div class="mt">
      <%= text_area_tag 'body', nil, size: '80x15' %>
    </div>
    <div class="mt"><%= submit_tag 'Зашифрувати' %></div>
  <% end -%>
</div>

app/views/decrypt_ceaser/index.html.erb
<p>
  <%= link_to 'Головна', root_path %>
</p>
<div class="text-center">
  <h1>Алгоритм дешифрування шифру зсуву на основі частотного аналізу:</h1>
  <p>Частотні таблиці для англійської мови: etaoinshrdlcumwfgypbvkjxqz</p>
  <% if @show %>
    <p>Зашифрований текст: <br/> <%= Result.last.before %></p>
    <p>Розшифрований текст: <br/> <%= Result.last.after %></p>
  <% end %>

  <%= form_tag(compute_decrypt_ceaser_index_path, method: :post) do -%>
    <p class="text-bold mt">Введіть зашифрований текст</p>
    <div class="mt">
      <%= text_area_tag 'body', nil, size: '80x15' %>
    </div>
    <div class="mt"><%= submit_tag 'Розшифрувати' %></div>
  <% end -%>
</div>

app/views/frequency_analysis/index.html.erb
<p>
  <%= link_to 'Головна', root_path %>
</p>
<div class="text-center">
  <h1>Частотні таблиці для української та англійської мов:</h1>
  <p>Частотні таблиці для української мови: оанвиіетклрсудмпбгзяєжїйхцчшщьюф</p>
  <p>Частотні таблиці для англійської мови: etaoinshrdlcumwfgypbvkjxqz</p>
  <%- if @frequency_analysis %>
    <p>Розрахований частотний аналіз: <%= @frequency_analysis %></p>
  <% end %>
  <%= form_tag(compute_frequency_analysis_index_path, method: :post) do -%>
    <p class="text-bold mt">Введіть текст для обчислення частотного аналізу</p>
    <div>
      <%= text_area_tag 'body', nil, size: '80x15' %>
    </div>
    <div class="mt"><%= submit_tag 'Розрахувати' %></div>
  <% end -%>
</div>

app/views/home/index.html.erb
<div class="text-center">
  <h1>Список алгоритмів:</h1>
  <p>
    <%= link_to 'Шифр зсуву для латинського та українсього алфавітів',
                ceaser_cipher_index_path %>
  </p>
  <p>
    <%= link_to 'Частотні таблиці для української та англійської мов', frequency_analysis_index_path %>
  </p>
  <p>
    <%= link_to 'Алгоритм дешифрування шифру зсуву на основі частотного аналізу', decrypt_ceaser_index_path %>
  </p>
  <p>
    <%= link_to 'Шифр Віженера для латинського та українсього алфавітів', vigenere_cipher_index_path %>
  </p>
  <p>
    <%= link_to 'RSA з використанням бінарного алгоритму піднесення до степеня за модулем', rsa_index_path %>
  </p>
  <p>Протокол обміну ключами Діффі-Гелмана</p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Crypto</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/rsa/index.html.erb
<p>
  <%= link_to 'Головна', root_path %>
</p>
<div class="text-center">
  <h1>RSA з використанням бінарного алгоритму піднесення до степеня за модулем:</h1>
  <% if @show %>
    <p>Введений текст: <br/> <%= Result.last.before %></p>
    <p>Текст після опрацювання: <br/> <%= Result.last.after %></p>
  <% end %>

  <%= form_tag(compute_rsa_index_path, method: :post) do -%>
    <p class="text-bold mt">Введіть текст</p>
    <div class="mt">
      <%= text_area_tag 'body', nil, size: '80x15' %>
    </div>
    <div class="mt"><%= submit_tag 'Опрацювати' %></div>
  <% end -%>
</div>

app/views/vigenere_cipher/index.html.erb
<p>
  <%= link_to 'Головна', root_path %>
</p>
<div class="text-center">
  <h1>Шифр Віженера для латинського та українсього алфавітів:</h1>
  <% if @show %>
    <p>Текст до: <br/> <%= Result.last.before %></p>
    <p>Текст після: <br/> <%= Result.last.after %></p>
  <% end %>

  <%= form_tag(compute_vigenere_cipher_index_path, method: :post) do -%>
    <div class="mt">
      Мова:
      <%= select_tag 'lang', options_for_select(["ua", "en"]), include_blank: false %>
    </div>
    <p class="text-bold mt">Введіть ключ(пр. 1,2,3)</p>
    <div class="mt">
      <%= text_field_tag 'seq', nil, width: '40' %>
    </div>
    <p class="text-bold mt">Введіть текст</p>
    <div class="mt">
      <%= text_area_tag 'body', nil, size: '80x15' %>
    </div>
    <div class="mt"><%= submit_tag 'Шифрувати' %></div>
  <% end -%>
</div>